# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Medium' do

pod 'AFNetworking', ‘2.4.1’
pod 'SDWebImage', '~>3.8.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'IQKeyboardManager'
pod 'MFSideMenu', '~> 0.5'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'Colours'
pod 'UITextView+Placeholder', '~> 1.2'
pod 'JTSImageViewController'
pod 'FTPopOverMenu'
pod ‘GSKStretchyHeaderView’
pod 'VENTokenField', '~> 2.0'
pod 'RSKImageCropper'

  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Medium

end
